language: node_js
node_js:
  - "node"
  - "6.11.2"
cache:
  directories:
    - node_modules
env:
  - CI=true
install: npm install
script: npm test
# https://gist.github.com/steffencrespo/829d0900f3314acffe462f2e552dd3f6
before_deploy:
  - npm install netlify-cli -g
  - npm run build
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: master