language: node_js
node_js:
  - "8"
  - "6.11.2"
cache:
  directories:
    - node_modules
install: npm install
script: 
  - CI=true npm test -- --coverage
  - CI="" npm run build
  - echo -n "youtube-lite.js.org" > build/CNAME
after_script: 
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
# https://medium.com/@sumn2u/automate-create-react-app-deployment-to-gh-pages-using-travis-ci-b2a97203680b
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master