language: node_js
node_js:
  - "8"
  - "6.11.2"
cache:
  directories:
    - node_modules
env:
  - CI=true
install: npm install
script: 
  - CI=true npm test -- --coverage
  - npm run build
after_script: 
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
  - npm run deploy