const C = {
  RECEIVE_SEARCH: "RECEIVE_SEARCH",
  REQUEST_SEARCH: "REQUEST_SEARCH",
  TOGGLE_DRAWER: "TOGGLE_DRAWER",
  ADD_VIDEO: "ADD_VIDEO",
  DELETE_VIDEO: "DELETE_VIDEO",
  ADD_PLAYLIST: "ADD_PLAYLIST",
  DELETE_PLAYLIST: "DELETE_PLAYLIST",
  ADJUST_SETTINGS: "ADJUST_SETTINGS",
  WATCH_VIDEO: "WATCH_VIDEO",
  START_VIDEO: "START_VIDEO",
  PAUSE_VIDEO: "PAUSE_VIDEO",
}

export default C
