# todo use github composite actions 
# (too lazy to do it because i would need to release the action to use it)
name: Build and preview
# https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks
on: [pull_request_target]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      # https://github.com/actions/cache/blob/main/examples.md#node---lerna
      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: install deps and run lint
        run: |
          # remove after stable version released
          sudo npm i -g npm@7
          npm i --verbose
          npm run bootstrap
          npm run lint
          npm run lint:ts
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: deploy app preview to surge
        env:
          PR_NUMBER: ${{ github.event.number }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo npm i -g npm@7
          npm i --verbose
          npm run bootstrap
          npm run prod:app
          # https://stackoverflow.com/questions/44491184/react-router-does-not-work-in-production-and-surge-deployments
          cp ./packages/app/dist/index.html ./packages/app/dist/200.html
          npx surge ./packages/app/dist "youtube-lite-app-preview-pr-${PR_NUMBER}.surge.sh" --token $SURGE_TOKEN
      - name: comment the preview link on PR
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREVIEW_LINK: youtube-lite-app-preview-pr-${{ github.event.number }}.surge.sh
        with:
          message: |
            See app preview at https://${{ env.PREVIEW_LINK }}
  # todo: make custom github action. not doing now because i'm feeling too lazy. it just works now
  preview-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: deploy storybook preview to surge
        env:
          PR_NUMBER: ${{ github.event.number }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo npm i -g npm@7
          npm i --verbose
          npm run bootstrap
          npm run build-storybook:app
          npx surge ./packages/app/storybook-static "youtube-lite-sb-preview-pr-${PR_NUMBER}.surge.sh" --token $SURGE_TOKEN
      - name: comment the preview link on PR
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREVIEW_LINK: youtube-lite-sb-preview-pr-${{ github.event.number }}.surge.sh
        with:
          message: |
            See storybook preview at https://${{ env.PREVIEW_LINK }}