# todo use github composite actions 
# (too lazy to do it because i would need to release the action to use it)
name: comment
# https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks
on: [pull_request_target]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: comment the app preview link on PR
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREVIEW_LINK: ytlite-${{ github.event.number }}.surge.sh
        with:
          header: app
          message: |
            See app preview at https://${{ env.PREVIEW_LINK }}
      - name: comment the storybook preview link on PR
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREVIEW_LINK: ytlitesb-${{ github.event.number }}.surge.sh
        with:
          header: storybook
          message: |
            See storybook preview at https://${{ env.PREVIEW_LINK }}